# Generated by Django 3.0.6 on 2020-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='search_history',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
